# Escalamiento de variables

Nombre: Valeria Estefanía Milke Loera

Fecha: 05-02-2026
_______

In [5]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_excel(r"C:\Users\valer\Boston_Housing_Dataset_1978.xlsx")
df.head(20)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3,222.0,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5,311.0,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5,311.0,15.2,386.71,17.10,18.9
10,0.22489,12.5,7.87,0.0,0.524,6.377,94.3,6.3467,5,311.0,15.2,392.52,20.45,15.0
11,0.11747,12.5,7.87,0.0,0.524,6.009,82.9,6.2267,5,311.0,15.2,396.90,13.27,18.9
12,0.09378,12.5,7.87,0.0,0.524,5.889,39.0,5.4509,5,311.0,15.2,390.50,15.71,21.7
13,0.62976,0.0,8.14,0.0,0.538,5.949,61.8,4.7075,4,307.0,21.0,396.90,8.26,20.4
14,0.63796,0.0,8.14,0.0,0.538,6.096,84.5,4.4619,4,307.0,21.0,380.02,10.26,18.2
15,0.62739,0.0,8.14,0.0,0.538,5.834,56.5,4.4986,4,307.0,21.0,395.62,8.47,19.9
16,1.05393,0.0,8.14,0.0,0.538,5.935,29.3,4.4986,4,307.0,21.0,386.85,6.58,23.1
17,0.78420,0.0,8.14,0.0,0.538,5.990,81.7,4.2579,4,307.0,21.0,386.75,14.67,17.5
18,0.80271,0.0,8.14,0.0,0.538,5.456,36.6,3.7965,4,307.0,21.0,288.99,11.69,20.2
19,0.72580,0.0,8.14,0.0,0.538,5.727,69.5,3.7965,4,307.0,21.0,390.95,11.28,18.2

______________
### Escalamiendo MinMax

In [17]:
dfscaled = df.copy()
for col in dfscaled.columns: 
    minn = dfscaled[col].min()
    dfscaled[col] = (dfscaled[col]-minn)
    maxx = dfscaled[col].max()
    dfscaled[col]/=maxx

In [18]:
dfscaled.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,452.000000
mean,0.127346,0.132953,0.331837,0.140765,0.103374,0.125663,0.582702,0.220534,0.115885,0.461954,0.101484,0.838346,0.300116,0.399324
std,0.240726,0.230487,0.258458,0.312765,0.237730,0.282253,0.334848,0.283180,0.306078,0.261537,0.222128,0.316008,0.185585,0.201570
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.004961,0.000000,0.124009,0.000000,0.009238,0.024891,0.312179,0.056885,0.004511,0.338448,0.036520,0.919550,0.157512,0.279176
50%,0.014514,0.000000,0.250901,0.000000,0.022084,0.028635,0.648503,0.122265,0.006015,0.415171,0.041339,0.984265,0.264688,0.358124
75%,0.082237,0.181000,0.652487,0.000000,0.037818,0.035131,0.898597,0.227476,0.034586,0.554140,0.044636,0.996760,0.406518,0.464531
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

___________
### Escalamiento

In [20]:
dfscaled2 = df.copy()
for col in dfscaled2.columns: 
    media = dfscaled2[col].mean()
    dfscaled2[col] = (dfscaled2[col]-media)
    std = dfscaled2[col].std()
    dfscaled2[col]/=std

In [21]:
dfscaled2.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,5.060000e+02,5.060000e+02,5.060000e+02,506.000000,5.060000e+02,5.060000e+02,5.060000e+02,506.000000,5.060000e+02,5.060000e+02,506.000000,5.060000e+02,5.060000e+02,4.520000e+02
mean,1.123388e-16,4.914821e-17,2.457411e-16,0.000000,-2.808469e-17,-2.808469e-17,1.404235e-17,0.000000,-5.616939e-17,-2.106352e-17,0.000000,-3.931857e-16,-4.388233e-17,-2.357996e-17
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000e+00,1.000000e+00
min,-5.290063e-01,-5.768333e-01,-1.283910e+00,-0.450065,-4.348387e-01,-4.452134e-01,-1.740200e+00,-0.778778,-3.786107e-01,-1.766301e+00,-0.456869,-2.652925e+00,-1.617134e+00,-1.981068e+00
25%,-5.083984e-01,-5.768333e-01,-8.041082e-01,-0.450065,-3.959800e-01,-3.570252e-01,-8.078969e-01,-0.577900,-3.638718e-01,-4.722298e-01,-0.292458,2.569683e-01,-7.684021e-01,-5.960586e-01
50%,-4.687134e-01,-5.768333e-01,-3.131484e-01,-0.450065,-3.419420e-01,-3.437630e-01,1.965119e-01,-0.347021,-3.589588e-01,-1.788774e-01,-0.270765,4.617600e-01,-1.909018e-01,-2.043959e-01
75%,-1.873840e-01,2.084605e-01,1.240628e+00,-0.450065,-2.757607e-01,-3.207470e-01,9.433994e-01,0.024515,-2.656120e-01,3.524779e-01,-0.255922,5.012980e-01,5.733277e-01,3.234971e-01
max,3.625091e+00,3.761807e+00,2.585188e+00,2.747221,3.771621e+00,3.097706e+00,1.246232e+00,2.752547,2.888526e+00,2.057243e+00,4.045031,5.115515e-01,3.771220e+00,2.979991e+00

________
### Histograma

In [ ]:
plt.figure(); plt.grid()
plt.hist(df["RM"])
plt.xlabel("RM original")
plt.title("Radio vs Ventas")
plt.show()